name: restaurant_rlutter_ui
description: restaurant_rlutter_ui

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^0.5.20+2
  datetime_picker_formfield: ^0.4.2
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  country_code_picker: ^1.6.2
  flutter_datetime_picker: ^1.4.0
  # local storage
  shared_preferences: ^0.5.12+4
  # http requests
  http: ^0.12.2

#  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/food1.jpg
    - img/food2.jpg
    - img/food3.jpg
    - img/food4.jpg
    - img/food5.jpg
    - img/food0.jpg
    - img/user1.jpg
    - img/user2.jpg
    - img/user3.jpg
    - img/user0.jpg
    - img/visa.png
    - img/paypal.png
    - img/apple_pay.png
    - img/brazil.png
    - img/canada.png
    - img/china.png
    - img/france.png
    - img/germany.png
    - img/italy.png
    - img/netherlands.png
    - img/spain.png
    - img/united-arab-emirates.png
    - img/united-states-of-america.png
    - img/marker.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Thin.ttf
        weight: 100
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
